#! /bin/bash
if [[ $1 -eq 0 ]];then
    echo "usage: $0 pid"
    exit
fi
      
TMPFILE="${TMPDIR:=/tmp}/pstack$$"

# Remove TMPFILE on termination
trap 'rm -f "$TMPFILE" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15

cat > "$TMPFILE" << EOF
set height 0
thread apply all where
detach
quit
EOF

gdb -batch -x $TMPFILE -p $1
