#!/bin/bash

SERVERS="redisproxy world gateload game gate login"

ls() {
    ps -ef |grep shaco |grep config
    ps -ef |grep commandd |grep lua
}
startone() {
    if [ $MEMCHECK -eq 0 ]
    then
        echo "start ${1}"
        ./shaco config_${1}.lua -d #> $HOME/log/${1}.log 2>&1
    else
        echo "start-memcheck ${1}"
        valgrind -v \
        --leak-check=full \
        --show-reachable=yes \
        --suppressions=shaco.supp \
        --log-file=$HOME/log/${1}.vallog \
        ./shaco config_${1}.lua -d #> $HOME/log/${1}.log 2>&1
    fi
    sleep ${2}
}
startcmdd() {
    cd tool && 2>&1 lua commandd.lua 0.0.0.0 7999 -d > ~/log/commandd.log
    ps -ef |grep commandd |grep lua
}
startall() {
    startone center 2
    for S in $SERVERS;do
        startone $S 0.5
    done
    sleep 1
    ls
}
start() {
    for S in $@;do
        startone $S 0.5
    done
    ls
}
stop() {
    if [ $MEMCHECK -eq 0 ]
    then pkill -2 shaco
    else pkill mem
    fi
}

USAGE="Usage: shaco-foot [startall] [startcmdd] [start [svr .. ]] [stop] [ls] -m"
MEMCHECK=0
CMD=$1
shift
while getopts ":m" optname
do
    case "$optname" in
    "m")
        MEMCHECK=1
        echo [memcheck mode]
        ;;
    *)
        #echo shout not be here
        ;;
    esac
done

case "$CMD" in
startall)
    startall
    ;;
start)
    shift
    start "$@"
    ;;
stop)
    stop
    ;;
startcmdd)
    startcmdd
    ;;
ls)
    ls
    ;;
*)
    echo $USAGE
    ;;
esac
