#!/bin/bash

ps -ef |grep shaco
echo "start gate"
./shaco config_gate.lua -d > gate.log
echo "start world"
./shaco config_world.lua -d > world.log
echo "start game"
./shaco config_game.lua -d > game.log
