#!/bin/bash

ps -ef |grep shaco
echo "start-memcheck center"
valgrind -v --leak-check=full --show-reachable=yes --suppressions=shaco.supp --log-file=shaco.center.vallog ./shaco config_center.lua -d > center.log
sleep 2
echo "start-memcheck world"
valgrind -v --leak-check=full --show-reachable=yes --suppressions=shaco.supp --log-file=shaco.world.vallog ./shaco config_world.lua -d > world.log
echo "start-memcheck world"
valgrind -v --leak-check=full --show-reachable=yes --suppressions=shaco.supp --log-file=shaco.world.vallog ./shaco config_world.lua -d > world.log
echo "start-memcheck game"
valgrind -v --leak-check=full --show-reachable=yes --suppressions=shaco.supp --log-file=shaco.game.vallog ./shaco config_game.lua -d > game.log
echo "start-memcheck gate"
valgrind -v --leak-check=full --show-reachable=yes --suppressions=shaco.supp --log-file=shaco.gate.vallog ./shaco config_gate.lua -d > gate.log
ps -ef |grep shaco
