#!/bin/bash

ps -ef |grep shaco
echo "start center"
./shaco config_center.lua -d > center.log
sleep 2
echo "start gate"
./shaco config_gate.lua -d > gate.log
echo "start world"
./shaco config_world.lua -d > world.log
echo "start game"
./shaco config_game.lua -d > game.log
ps -ef |grep shaco
